default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: password
  socket: /tmp/mysql.sock
  host: db

development:
  <<: *default
  database: lifehack_development

production:
  <<: *default
  database: Lifehack_production
  adapter: mysql2
  charset: utf8mb4
  host: <%= Rails.application.credentials.db[:endpoint] %>
  username: <%= Rails.application.credentials.db[:user_name] %>
  password: <%= Rails.application.credentials.db[:password] %>
