# このファイルを修正する際には，必ずサーバを再起動してください．
# 秘密鍵は, 署名されたクッキーの整合性を検証するために使用されます.
# このキーを変更すると, 古い署名付きクッキーはすべて無効になります!
# 秘密鍵は30文字以上ですべてランダムであることを確認してください。
# 規則的な単語は使わないでください。そうしないと、辞書攻撃を受けてしまいます。
# 安全な秘密鍵を生成するために、`rails secret`を使用することができます。
# このファイルに書かれた秘密が秘密裏に守られていることを確認してください。
# コードを公開している場合。
# 共有された秘密はすべての環境で利用できます。
# 共有されます。
# api_key: a1B2c3D4e5F6
# 環境の秘密は、その特定の環境でのみ利用可能です。
development:
  secret_key_base: f686ea242715b3a6930b9ba106fc79face034d3ca28064bb6c6e2ef19b71e2bfde115a20a88174a5738179427117b7eba939c9ca8c8d82efc8da097813f02b5d
test:
  secret_key_base: 81aefcea91b67fe9e12b28f116795745e8b5b453ff594137fc5abc48abb9f4789244faf55be746e0fdfc2c7d23f908da8d562a8c491a8d2666436c424b8125fa
# プロダクションシークレットを暗号化されていないシークレットファイルに保持しないでください。
# 代わりに、環境から値を読み込む。
# または、`bin/rails secrets:setup` を使って、暗号化された秘密を設定します。
# または、`bin/rails secrets:setup` で暗号化された秘密を設定し、`production:` 環境をそこに移動します。
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
